x <- c(1, 6, 13, -4, 51)
y <- c(2, 13, 4, 25, 16)

correlation1 <- cor(x, y, method = "pearson")
print("Correlations about various methods are : ")
print(correlation1)
correlation2 <- cor(x, y, method = "spearman")
print(correlation2)
correlation3 <- cor(x, y, method = "kendall")
print(correlation3)
